// Generated by CoffeeScript 1.6.2
(function() {
  var app, assert;

  app = require("../app");

  assert = require("assert");

  describe("hello()", function() {
    return it("should return Hello world!", function() {
      return assert(app.hello(), "Hello world!");
    });
  });

}).call(this);
